# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: Pere Giménez <gimenezfebrer@gmail.com>
CodeOfConductContact: gimenezfebrer@gmail.com
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Pere Giménez
MarkdownIndentation: 2
PackageName: StateSignals
PackageOwner: sciflydev
PackageUUID: cc7ea9f4-611f-50b7-86a5-d62288be5013
_commit: v0.14.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
