name = "StateSignals"
uuid = "cc7ea9f4-611f-50b7-86a5-d62288be5013"
authors = ["Pere Giménez <gimenezfebrer@gmail.com>"]
version = "0.3.1"

[deps]
Signals = "6303bc30-01ab-52eb-8b10-60e47555a8d1"

[compat]
Signals = "1"
julia = "1.10"
